name: build-_site
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - run: bundle install
      - run: bundle exec jekyll build
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'add _site [skip ci]'
          file_pattern: '_site/**'
          add_options: '--force'
